heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - https://els.xxx.tech
    - https://kibana.xxx.tech
    - https://api.dev.xxx.tech/identity/health

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'